# Generated by Django 3.2.4 on 2021-06-30 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App", "\u200f\u200f0015_demo_website_test_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="is_confirmed",
        ),
        migrations.AlterField(
            model_name="website_profile",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wp_profile_ID",
                to="App.profile",
            ),
        ),
        migrations.CreateModel(
            name="Website_Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_ID",
                        to="App.business",
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wb_website_ID",
                        to="App.website",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="business",
            name="websites",
            field=models.ManyToManyField(
                through="App.Website_Business", to="App.Website"
            ),
        ),
        migrations.AddField(
            model_name="website",
            name="businesses",
            field=models.ManyToManyField(
                through="App.Website_Business", to="App.Business"
            ),
        ),
        migrations.AddConstraint(
            model_name="website_business",
            constraint=models.UniqueConstraint(
                fields=("website", "business"), name="website_business"
            ),
        ),
    ]
