# Generated by Django 3.2.5 on 2021-06-30 03:52

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_auto_20210630_0043"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                blank=True, max_length=63, null=True
            ),
        ),
    ]
