# Generated by Django 3.2.3 on 2021-05-23 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=None)),
                ('URL', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('facebook_link', models.TextField(blank=True, null=True)),
                ('instagram_link', models.TextField(blank=True, null=True)),
                ('picture_0', models.ImageField(blank=True, null=True, upload_to=None)),
                ('picture_1', models.ImageField(blank=True, null=True, upload_to=None)),
                ('picture_2', models.ImageField(blank=True, null=True, upload_to=None)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.profile')),
            ],
        ),
    ]
