# Generated by Django 3.2.5 on 2021-07-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_auto_20210630_0352"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="logo",
            field=models.ImageField(
                default="App/images/WebsitesLogos/default.jpg",
                upload_to="App/images/WebsitesLogos/",
            ),
        ),
    ]
