# Generated by Django 3.2.3 on 2021-05-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_test_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="URL",
            field=models.URLField(default=None, max_length=250),
        ),
    ]
