# Generated by Django 3.2.3 on 2021-05-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210523_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='from_hour',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='business',
            name='to_hour',
            field=models.TimeField(default=None),
        ),
    ]
