# Generated by Django 3.2.4 on 2021-06-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_sale_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="URL",
        ),
    ]
