# Generated by Django 3.2.5 on 2021-07-11 09:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_alter_website_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="number_of_slides_in_main_page",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "picture",
                    models.ImageField(
                        default=None, upload_to="App/images/SlidePictures/"
                    ),
                ),
                ("description", models.CharField(default=None, max_length=200)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App.website"
                    ),
                ),
            ],
        ),
    ]
