# Generated by Django 3.2.3 on 2021-05-23 13:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20210523_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=False, max_length=128, region=None),
        ),
    ]
