# Generated by Django 3.2.4 on 2021-06-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0004_remove_sale_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="description",
            field=models.TextField(default=None),
        ),
    ]
