# Generated by Django 3.2.3 on 2021-05-23 13:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_business_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
