# Generated by Django 3.2.4 on 2021-06-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0005_alter_business_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="picture",
            field=models.ImageField(
                default="App/images/SalesPictures/default.jpg",
                upload_to="App/images/SalesPictures/",
            ),
        ),
    ]
