# Generated by Django 3.2.4 on 2021-06-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0006_alter_sale_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
