# Generated by Django 3.2.4 on 2021-06-13 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0007_sale_is_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="profile",
            field=models.ForeignKey(
                default=4, on_delete=django.db.models.deletion.CASCADE, to="App.profile"
            ),
            preserve_default=False,
        ),
    ]
