# Generated by Django 3.2.3 on 2021-05-23 15:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20210523_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='URL',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='from_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(default=None, upload_to='images/BusinessesLogos/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='business',
            name='picture_0',
            field=models.ImageField(blank=True, null=True, upload_to='images/BusinessesPictures/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/BusinessesPictures/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/BusinessesPictures/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='to_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
