from django.db import migrations, transaction


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0007_categories_test_data"),
    ]

    def generate_data(apps, schema_editor):
        from App.models import Business_Image, Business
        from django.shortcuts import get_object_or_404

        business_image_test_data = [
            (1, "App/images/BusinessesGallery/matt_does_fitness_1.jfif"),
            (1, "App/images/BusinessesGallery/matt_does_fitness_2.jfif"),
            (1, "App/images/BusinessesGallery/matt_does_fitness_3.jfif"),
            (1, "App/images/BusinessesGallery/matt_does_fitness_4.jfif"),
            (1, "App/images/BusinessesGallery/matt_does_fitness_5.jfif"),
            (2, "App/images/BusinessesGallery/space_florentin_1.jfif"),
            (2, "App/images/BusinessesGallery/space_florentin_2.jfif"),
            (2, "App/images/BusinessesGallery/space_florentin_3.jfif"),
            (2, "App/images/BusinessesGallery/space_florentin_4.jpg"),
            (2, "App/images/BusinessesGallery/space_florentin_5.jfif"),
            (3, "App/images/BusinessesGallery/lake_tlv_1.png"),
            (3, "App/images/BusinessesGallery/lake_tlv_2.jpg"),
            (3, "App/images/BusinessesGallery/lake_tlv_3.jpg"),
            (3, "App/images/BusinessesGallery/lake_tlv_4.jfif"),
            (3, "App/images/BusinessesGallery/lake_tlv_5.jfif"),
            (
                4,
                "App/images/BusinessesGallery/vegan_business_1_1.jpg",
            ),
            (
                4,
                "App/images/BusinessesGallery/vegan_business_1_2.jpg",
            ),
            (
                4,
                "App/images/BusinessesGallery/vegan_business_1_3.jfif",
            ),
            (
                4,
                "App/images/BusinessesGallery/vegan_business_1_4.jpg",
            ),
            (
                4,
                "App/images/BusinessesGallery/vegan_business_1_5.jpg",
            ),
            (
                5,
                "App/images/BusinessesGallery/vegan_business_2_1.jfif",
            ),
            (
                5,
                "App/images/BusinessesGallery/vegan_business_2_2.png",
            ),
            (
                5,
                "App/images/BusinessesGallery/vegan_business_2_3.jpg",
            ),
            (
                5,
                "App/images/BusinessesGallery/vegan_business_2_4.jpg",
            ),
            (
                5,
                "App/images/BusinessesGallery/vegan_business_2_5.jpg",
            ),
            (
                6,
                "App/images/BusinessesGallery/vegan_business_3_1.jfif",
            ),
            (
                6,
                "App/images/BusinessesGallery/vegan_business_3_2.png",
            ),
            (
                6,
                "App/images/BusinessesGallery/vegan_business_3_3.jpeg",
            ),
            (
                6,
                "App/images/BusinessesGallery/vegan_business_3_4.jpg",
            ),
            (
                6,
                "App/images/BusinessesGallery/vegan_business_3_5.jfif",
            ),
            (
                7,
                "App/images/BusinessesGallery/coffe_botique_1.jpg",
            ),
            (
                7,
                "App/images/BusinessesGallery/coffe_botique_2.jfif",
            ),
            (
                7,
                "App/images/BusinessesGallery/coffe_botique_3.jfif",
            ),
            (
                7,
                "App/images/BusinessesGallery/coffe_botique_4.jpg",
            ),
            (
                7,
                "App/images/BusinessesGallery/coffe_botique_5.jfif",
            ),
            (
                8,
                "App/images/BusinessesGallery/ninja_1.jpg",
            ),
            (
                8,
                "App/images/BusinessesGallery/ninja_2.jpg",
            ),
            (
                8,
                "App/images/BusinessesGallery/ninja_3.jpg",
            ),
            (
                8,
                "App/images/BusinessesGallery/ninja_4.jfif",
            ),
            (
                8,
                "App/images/BusinessesGallery/ninja_5.jfif",
            ),
            (
                9,
                "App/images/BusinessesGallery/butcher_1.jpg",
            ),
            (
                9,
                "App/images/BusinessesGallery/butcher_2.jpeg",
            ),
            (
                9,
                "App/images/BusinessesGallery/butcher_3.jpg",
            ),
            (
                9,
                "App/images/BusinessesGallery/butcher_4.jfif",
            ),
            (
                9,
                "App/images/BusinessesGallery/butcher_5.jpg",
            ),
            (
                10,
                "App/images/BusinessesGallery/candy_shop_1.jfif",
            ),
            (
                10,
                "App/images/BusinessesGallery/candy_shop_2.jfif",
            ),
            (
                10,
                "App/images/BusinessesGallery/candy_shop_3.jpg",
            ),
            (
                10,
                "App/images/BusinessesGallery/candy_shop_4.jpg",
            ),
            (
                10,
                "App/images/BusinessesGallery/candy_shop_5.png",
            ),
            (
                11,
                "App/images/BusinessesGallery/weights_shop_1.jpg",
            ),
            (
                11,
                "App/images/BusinessesGallery/weights_shop_2.jfif",
            ),
            (
                11,
                "App/images/BusinessesGallery/weights_shop_3.jfif",
            ),
            (
                11,
                "App/images/BusinessesGallery/weights_shop_4.jpg",
            ),
            (
                11,
                "App/images/BusinessesGallery/weights_shop_5.jpg",
            ),
            (
                12,
                "App/images/BusinessesGallery/my_protein_1.jfif",
            ),
            (
                12,
                "App/images/BusinessesGallery/my_protein_2.jfif",
            ),
            (
                12,
                "App/images/BusinessesGallery/my_protein_3.jfif",
            ),
            (
                12,
                "App/images/BusinessesGallery/my_protein_4.png",
            ),
            (
                12,
                "App/images/BusinessesGallery/my_protein_5.jpg",
            ),
            (
                13,
                "App/images/BusinessesGallery/crafting_shop_1.jfif",
            ),
            (
                13,
                "App/images/BusinessesGallery/crafting_shop_2.jpg",
            ),
            (
                13,
                "App/images/BusinessesGallery/crafting_shop_3.jfif",
            ),
            (
                13,
                "App/images/BusinessesGallery/crafting_shop_4.jfif",
            ),
            (
                13,
                "App/images/BusinessesGallery/crafting_shop_5.jfif",
            ),
            (
                14,
                "App/images/BusinessesGallery/chocolate_botique_1.jpg",
            ),
            (
                14,
                "App/images/BusinessesGallery/chocolate_botique_2.jfif",
            ),
            (
                14,
                "App/images/BusinessesGallery/chocolate_botique_3.jpg",
            ),
            (
                14,
                "App/images/BusinessesGallery/chocolate_botique_4.jpg",
            ),
            (
                14,
                "App/images/BusinessesGallery/chocolate_botique_5.jpg",
            ),
            (
                15,
                "App/images/BusinessesGallery/dairy_queen_1.jfif",
            ),
            (
                15,
                "App/images/BusinessesGallery/dairy_queen_2.jpg",
            ),
            (
                15,
                "App/images/BusinessesGallery/dairy_queen_3.jpg",
            ),
            (
                15,
                "App/images/BusinessesGallery/dairy_queen_4.jpg",
            ),
            (
                15,
                "App/images/BusinessesGallery/dairy_queen_5.jpg",
            ),
            (
                16,
                "App/images/BusinessesGallery/the_old_fisherman_1.jpg",
            ),
            (
                16,
                "App/images/BusinessesGallery/the_old_fisherman_2.jfif",
            ),
            (
                16,
                "App/images/BusinessesGallery/the_old_fisherman_3.jpg",
            ),
            (
                16,
                "App/images/BusinessesGallery/the_old_fisherman_4.jfif",
            ),
            (
                16,
                "App/images/BusinessesGallery/the_old_fisherman_5.jpg",
            ),
            (
                17,
                "App/images/BusinessesGallery/knife_master_1.jfif",
            ),
            (
                17,
                "App/images/BusinessesGallery/knife_master_2.jfif",
            ),
            (
                17,
                "App/images/BusinessesGallery/knife_master_3.jfif",
            ),
            (
                17,
                "App/images/BusinessesGallery/knife_master_4.jfif",
            ),
            (
                17,
                "App/images/BusinessesGallery/knife_master_5.jpg",
            ),
            (
                18,
                "App/images/BusinessesGallery/grill_store_1.jfif",
            ),
            (
                18,
                "App/images/BusinessesGallery/grill_store_2.jfif",
            ),
            (
                18,
                "App/images/BusinessesGallery/grill_store_3.jfif",
            ),
            (
                18,
                "App/images/BusinessesGallery/grill_store_4.jfif",
            ),
            (
                18,
                "App/images/BusinessesGallery/grill_store_5.jfif",
            ),
            (
                19,
                "App/images/BusinessesGallery/shoe_store_1.jpg",
            ),
            (
                19,
                "App/images/BusinessesGallery/shoe_store_2.jfif",
            ),
            (
                19,
                "App/images/BusinessesGallery/shoe_store_3.jpg",
            ),
            (
                19,
                "App/images/BusinessesGallery/shoe_store_4.jfif",
            ),
            (
                19,
                "App/images/BusinessesGallery/shoe_store_5.jfif",
            ),
            (
                20,
                "App/images/BusinessesGallery/sports_wear_1.jfif",
            ),
            (
                20,
                "App/images/BusinessesGallery/sports_wear_2.jfif",
            ),
            (
                20,
                "App/images/BusinessesGallery/sports_wear_3.jfif",
            ),
            (
                20,
                "App/images/BusinessesGallery/sports_wear_4.jfif",
            ),
            (
                20,
                "App/images/BusinessesGallery/sports_wear_5.jfif",
            ),
            (
                21,
                "App/images/BusinessesGallery/sports_equipment_1.jfif",
            ),
            (
                21,
                "App/images/BusinessesGallery/sports_equipment_2.jfif",
            ),
            (
                21,
                "App/images/BusinessesGallery/sports_equipment_3.jfif",
            ),
            (
                21,
                "App/images/BusinessesGallery/sports_equipment_4.jfif",
            ),
            (
                21,
                "App/images/BusinessesGallery/sports_equipment_5.jfif",
            ),
            (
                22,
                "App/images/BusinessesGallery/climbing_store_1.jfif",
            ),
            (
                22,
                "App/images/BusinessesGallery/climbing_store_2.jfif",
            ),
            (
                22,
                "App/images/BusinessesGallery/climbing_store_3.jfif",
            ),
            (
                22,
                "App/images/BusinessesGallery/climbing_store_4.jfif",
            ),
            (
                22,
                "App/images/BusinessesGallery/climbing_store_5.jfif",
            ),
            (
                23,
                "App/images/BusinessesGallery/diving_store_1.jfif",
            ),
            (
                23,
                "App/images/BusinessesGallery/diving_store_2.jfif",
            ),
            (
                23,
                "App/images/BusinessesGallery/diving_store_3.jfif",
            ),
            (
                23,
                "App/images/BusinessesGallery/diving_store_4.jfif",
            ),
            (
                23,
                "App/images/BusinessesGallery/diving_store_5.jfif",
            ),
            (
                24,
                "App/images/BusinessesGallery/bones_restaurant_1.jfif",
            ),
            (
                24,
                "App/images/BusinessesGallery/bones_restaurant_2.jfif",
            ),
            (
                24,
                "App/images/BusinessesGallery/bones_restaurant_3.jfif",
            ),
            (
                24,
                "App/images/BusinessesGallery/bones_restaurant_4.jfif",
            ),
            (
                24,
                "App/images/BusinessesGallery/bones_restaurant_5.jfif",
            ),
            (
                25,
                "App/images/BusinessesGallery/coffee_machine_1.jfif",
            ),
            (
                25,
                "App/images/BusinessesGallery/coffee_machine_2.jfif",
            ),
            (
                25,
                "App/images/BusinessesGallery/coffee_machine_3.jfif",
            ),
            (
                25,
                "App/images/BusinessesGallery/coffee_machine_4.jfif",
            ),
            (
                25,
                "App/images/BusinessesGallery/coffee_machine_5.jfif",
            ),
            (26, "App/images/BusinessesGallery/coffee_house_1.jfif"),
            (26, "App/images/BusinessesGallery/coffee_house_2.jfif"),
            (26, "App/images/BusinessesGallery/coffee_house_3.jfif"),
            (26, "App/images/BusinessesGallery/coffee_house_4.jfif"),
            (26, "App/images/BusinessesGallery/coffee_house_5.jfif"),
        ]

        with transaction.atomic():
            for business_id, image in business_image_test_data:
                business_image = Business_Image(
                    business=get_object_or_404(Business, pk=business_id),
                    image=image,
                )
                business_image.save()

    operations = [
        migrations.RunPython(generate_data),
    ]
