# Generated by Django 3.2.4 on 2021-06-14 18:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0008_sale_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="description",
            field=ckeditor.fields.RichTextField(default=None),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="description",
            field=models.TextField(default=None, max_length=50),
        ),
    ]
