# Generated by Django 3.2.3 on 2021-05-23 15:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20210523_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
