# Generated by Django 3.2.3 on 2021-05-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_business_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(default=None, upload_to='App/images/BusinessesLogos/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='picture_0',
            field=models.ImageField(blank=True, null=True, upload_to='App/images/BusinessesPictures/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='App/images/BusinessesPictures/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='App/images/BusinessesPictures/'),
        ),
    ]
