# Generated by Django 3.2.4 on 2021-06-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0009_auto_20210614_1852"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="picture",
            field=models.ImageField(
                default=None, upload_to="App/images/SalesPictures/"
            ),
        ),
    ]
