# Generated by Django 3.2.4 on 2021-06-15 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0010_alter_sale_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "logo",
                    models.ImageField(
                        default=None, upload_to="App/images/WebsitesLogos/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Website_Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_ID",
                        to="App.profile",
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_ID",
                        to="App.website",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="website",
            name="profiles",
            field=models.ManyToManyField(
                through="App.Website_Profile", to="App.Profile"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="websites",
            field=models.ManyToManyField(
                through="App.Website_Profile", to="App.Website"
            ),
        ),
        migrations.AddConstraint(
            model_name="website_profile",
            constraint=models.UniqueConstraint(
                fields=("profile", "website"), name="profile_website"
            ),
        ),
    ]
