# Generated by Django 3.2.4 on 2021-06-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0011_auto_20210615_1832"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
