# Generated by Django 3.2.4 on 2021-06-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0012_website_is_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="website_profile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
