# Generated by Django 3.2.4 on 2021-06-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0013_website_profile_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="logo",
            field=models.ImageField(
                default="App/images/SalesPictures/default.jpg",
                upload_to="App/images/WebsitesLogos/",
            ),
        ),
    ]
