# Generated by Django 3.2.5 on 2021-07-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "\u200f\u200f0018_businesses_test_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="logo",
            field=models.ImageField(
                default="App/images/default.jpg",
                upload_to="App/images/BusinessesLogos/",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="picture",
            field=models.ImageField(
                default="App/images/WebsitesLogos/default.jpg",
                upload_to="App/images/SalesPictures/",
            ),
        ),
        migrations.AlterField(
            model_name="slide",
            name="picture",
            field=models.ImageField(
                default="App/images/default.jpg", upload_to="App/images/SlidePictures/"
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="logo",
            field=models.ImageField(
                default="App/images/default.jpg", upload_to="App/images/WebsitesLogos/"
            ),
        ),
    ]
