from django.db import migrations, transaction


class Migration(migrations.Migration):
    dependencies = [
        ("App", "‏‏0005_businesses_test_data"),
    ]

    def generate_data(apps, schema_editor):
        from App.models import Sale, Profile, Business
        from django.shortcuts import get_object_or_404

        sales_test_data = [
            (
                21,
                1,
                "Sale demo 1",
                "description description description description description description",
                "App/images/SalesPictures/demo_sale_1.png",
                Sale.SaleStatus.APPROVED,
            ),
            (
                21,
                3,
                "Sale demo 2",
                "description description description description description description",
                "App/images/SalesPictures/demo_sale_2.png",
                Sale.SaleStatus.APPROVED,
            ),
            (
                21,
                6,
                "30% discount on rosemary oil",
                "And other various diescounts on our oils!",
                "App/images/SalesPictures/vegan_sale_2.png",
                Sale.SaleStatus.APPROVED,
            ),
            (
                21,
                4,
                "Special offers on orders on Friday!",
                "Reservations can be made until Wednesday at 16:00",
                "App/images/SalesPictures/vegan_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                7,
                "Colombia coffee beans",
                "Strong and full body aroma",
                "App/images/SalesPictures/coffe_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                7,
                "Guatemala coffee beans",
                "Long roast earthy flavor",
                "App/images/SalesPictures/coffee_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                7,
                "Indonesia coffee beans",
                "Sweet chocolate flavor",
                "App/images/SalesPictures/coffee_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                7,
                "Brazil coffee beans",
                "Strong flavor full with aroma",
                "App/images/SalesPictures/coffee_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                7,
                "Simple coffee machine",
                "Making coffee from grounded coffee",
                "App/images/SalesPictures/coffee_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                7,
                "Superior coffe machine",
                "Making coffee from grounded coffee, and can foam the milk",
                "App/images/SalesPictures/coffee_sale_6.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                7,
                "Mini industrial",
                "single side industrial coffee machine",
                "App/images/SalesPictures/coffee_sale_7.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                7,
                "Full industrial",
                "Double sided industrial coffee machine",
                "App/images/SalesPictures/coffee_sale_8.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                7,
                "Makineta",
                "Travlers coffee machine for a true coffee lovers",
                "App/images/SalesPictures/coffee_sale_9.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                7,
                "Cold press",
                "Easy coffee making with strong pressure and now heat needed",
                "App/images/SalesPictures/coffee_sale_10.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                8,
                "Ninja food processor",
                "The strongest food processor in the market",
                "App/images/SalesPictures/ninja_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                8,
                "Ninja blender",
                "The strongest blender in the market",
                "App/images/SalesPictures/ninja_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                8,
                "Ninja all in one",
                "Its a blender and a food processor",
                "App/images/SalesPictures/ninja_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                8,
                "Ninja Grill",
                "Strong grill that easy to clean",
                "App/images/SalesPictures/ninja_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                8,
                "Smootie on the way",
                "small comport smootie bkender ",
                "App/images/SalesPictures/ninja_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                9,
                "Antricot",
                "Marbel filet antricot",
                "App/images/SalesPictures/butcher_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                9,
                "Sinta",
                "Low fat beef ",
                "App/images/SalesPictures/butcher_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                9,
                "Filet mingion",
                "The king of the meats",
                "App/images/SalesPictures/butcher_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                9,
                "Norweign salmon",
                "Fresh wild salmon",
                "App/images/SalesPictures/butcher_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                9,
                "Lavrak",
                "Healthy fish",
                "App/images/SalesPictures/butcher_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                9,
                "Tuna",
                "Yellowfin tuna",
                "App/images/SalesPictures/butcher_sale_6.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                9,
                "Chicken breast",
                "Clean chicken breast",
                "App/images/SalesPictures/butcher_sale_7.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                9,
                "Spring chicken",
                "fully flavored chicken part",
                "App/images/SalesPictures/butcher_sale_8.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                10,
                "Werther's original",
                "Butterscotch candy",
                "App/images/SalesPictures/candies_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                10,
                "Skittles",
                "Milk chocolate candy",
                "App/images/SalesPictures/candies_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                10,
                "Jelly bean candy",
                "Sweet and sour candy",
                "App/images/SalesPictures/candies_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                10,
                "Sour strips",
                "All are loving them",
                "App/images/SalesPictures/candies_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                10,
                "M&M",
                "The ultimate chocolate candy of all time",
                "App/images/SalesPictures/candies_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                10,
                "Pez",
                "Sweet candies that come with a bubble head toy",
                "App/images/SalesPictures/candies_sale_6.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                10,
                "Sour patch",
                "The most sour candy",
                "App/images/SalesPictures/candies_sale_7.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                11,
                "Changeable dumbbell",
                "Iron handle with iron plates",
                "App/images/SalesPictures/fitness_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                11,
                "2 KG dumbbells",
                "Set of two",
                "App/images/SalesPictures/fitness_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                11,
                "2 KG dumbbell",
                "Single set",
                "App/images/SalesPictures/fitness_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                11,
                "Full bench press set",
                "3 bars, one bed and 40kg plates",
                "App/images/SalesPictures/fitness_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                11,
                "Adjustment dumbbell",
                "Up to 42kg",
                "App/images/SalesPictures/fitness_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                11,
                "Plate set",
                "from 10kg to 80kg",
                "App/images/SalesPictures/fitness_sale_6.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                12,
                "Clear whey",
                "Fruit juice low calories filled with protein",
                "App/images/SalesPictures/myprotein_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                12,
                "Layerd protein bar",
                "Sweet treat after a workout",
                "App/images/SalesPictures/myprotein_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                12,
                "Whey protein",
                "Low calories shake",
                "App/images/SalesPictures/myprotein_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                12,
                "Brownies",
                "sweet protein treat",
                "App/images/SalesPictures/myprotein_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                12,
                "The whey",
                "protein pwoder",
                "App/images/SalesPictures/myprotein_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                12,
                "Multi vitamin",
                "For men",
                "App/images/SalesPictures/myprotein_sale_6.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                12,
                "Bcaa",
                "energy drink",
                "App/images/SalesPictures/myprotein_sale_7.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                13,
                "Markers",
                "Rainbow color set",
                "App/images/SalesPictures/crafting_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                13,
                "Canvas",
                "Size 120x80 cm",
                "App/images/SalesPictures/crafting_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                13,
                "Oil paint",
                "Made for canvas painting",
                "App/images/SalesPictures/crafting_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                13,
                "Raping paper",
                "Different king shape and color",
                "App/images/SalesPictures/crafting_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                13,
                "Scissors",
                "Trendi scissors",
                "App/images/SalesPictures/crafting_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                13,
                "Painting brushes",
                "Set of painting brush",
                "App/images/SalesPictures/crafting_sale_6.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Square perline chocolate",
                "Dark and milk",
                "App/images/SalesPictures/choclate_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Chocolate bar",
                "Milk Chocolate with salted caramel",
                "App/images/SalesPictures/choclate_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Artistic perline set",
                "Filled with nuggat cream",
                "App/images/SalesPictures/choclate_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Perlines",
                "Dark, Milk, with nuts and more...",
                "App/images/SalesPictures/choclate_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Valentines box",
                "Semi sweet dark chocolate",
                "App/images/SalesPictures/choclate_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Pink bar",
                "White chocolate with pink himalayan salt",
                "App/images/SalesPictures/choclate_sale_6.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Chocolate spread",
                "Speacial home made chocolate",
                "App/images/SalesPictures/choclate_sale_7.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Chocolate cake",
                "Tall creamy nuty chocolate cake",
                "App/images/SalesPictures/choclate_sale_8.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Artistic perlines",
                "Beautiful perlines in units",
                "App/images/SalesPictures/choclate_sale_9.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                15,
                "Milk",
                "Milk from free range cows",
                "App/images/SalesPictures/dairy_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                15,
                "Parmesan",
                "Parmesan origiano from free range cows",
                "App/images/SalesPictures/dairy_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                15,
                "Cream cheese",
                "fat cheese with 27%",
                "App/images/SalesPictures/dairy_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                15,
                "Cheddar cheese",
                "yellow and orange cheddar cheese",
                "App/images/SalesPictures/dairy_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                15,
                "Gorgonzola",
                "Blue cheese with smoked taste",
                "App/images/SalesPictures/dairy_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                15,
                "Yugort",
                "Yugort from free range cows",
                "App/images/SalesPictures/dairy_sale_6.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                15,
                "Ice cream",
                "Home made ice cream",
                "App/images/SalesPictures/dairy_sale_7.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                15,
                "Mozzarella",
                "Mozzarella from free range cheese",
                "App/images/SalesPictures/dairy_sale_8.jpg",
                Sale.SaleStatus.APPROVED,
            ),
        ]

        with transaction.atomic():
            for (
                profile_id,
                business_id,
                title,
                description,
                picture,
                is_confirmed,
            ) in sales_test_data:
                sale = Sale(
                    profile=get_object_or_404(Profile, pk=profile_id),
                    business=get_object_or_404(Business, pk=business_id),
                    title=title,
                    picture=picture,
                    description=description,
                    is_confirmed=is_confirmed,
                )
                sale.save()

    operations = [
        migrations.RunPython(generate_data),
    ]
