from django.db import migrations, transaction


class Migration(migrations.Migration):
    dependencies = [
        ("App", "‏‏0005_businesses_test_data"),
    ]

    def generate_data(apps, schema_editor):
        from App.models import Sale, Profile, Business
        from django.shortcuts import get_object_or_404

        sales_test_data = [
            (
                21,
                3,
                "Single entry",
                "100 nis",
                "App/images/SalesPictures/lake_tlv_1.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                21,
                3,
                "12 pass ticket",
                "1,000 nis until the end of the year",
                "App/images/SalesPictures/lake_tlv_2.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                21,
                6,
                "30% discount on rosemary oil",
                "And other various diescounts on our oils!",
                "App/images/SalesPictures/vegan_sale_2.png",
                Sale.SaleStatus.APPROVED,
            ),
            (
                21,
                4,
                "Special offers on orders on Friday!",
                "Reservations can be made until Wednesday at 16:00",
                "App/images/SalesPictures/vegan_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                7,
                "Colombia coffee beans",
                "On the weeekends only!",
                "App/images/SalesPictures/coffee_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                7,
                "Guatemala coffee beans",
                "On the weeekends only!",
                "App/images/SalesPictures/coffee_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                7,
                "Indonesia coffee beans",
                "30% discount when buying 200 grams or more",
                "App/images/SalesPictures/coffee_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                7,
                "Brazil coffee beans",
                "1 + 1 on the small size",
                "App/images/SalesPictures/coffee_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                15,
                25,
                "Simple coffee machine",
                "10% discount",
                "App/images/SalesPictures/coffee_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                15,
                25,
                "Superior coffe machine",
                "Comes with a free fpaming cup",
                "App/images/SalesPictures/coffee_sale_6.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                15,
                25,
                "Mini industrial",
                "Comes with 5 years of free fixing",
                "App/images/SalesPictures/coffee_sale_7.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                15,
                25,
                "Full industrial",
                "30% discount only for a week!!",
                "App/images/SalesPictures/coffee_sale_8.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                15,
                25,
                "Makineta",
                "Comes with a free cups holder",
                "App/images/SalesPictures/coffee_sale_9.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                15,
                25,
                "Cold press",
                "10% discount untill the end of the year",
                "App/images/SalesPictures/coffee_sale_10.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                8,
                "Ninja food processor",
                "Comes with 5 different knifes only for 2 weeks",
                "App/images/SalesPictures/ninja_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                8,
                "Ninja blender",
                "2 years guarantee",
                "App/images/SalesPictures/ninja_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                8,
                "Ninja all in one",
                "15% discount for 1 week only!",
                "App/images/SalesPictures/ninja_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                8,
                "Ninja Grill",
                "20% off when buying ninja blender",
                "App/images/SalesPictures/ninja_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                8,
                "Smootie on the way",
                "10% off only in Sunday",
                "App/images/SalesPictures/ninja_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                9,
                "Antricot",
                "Buy 2 KG and get 20% discount",
                "App/images/SalesPictures/butcher_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                9,
                "Sinta",
                "Buy 1 KG and get 50% off the chicken breast",
                "App/images/SalesPictures/butcher_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                9,
                "Filet mingion",
                "200 nis only in Friday!",
                "App/images/SalesPictures/butcher_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                9,
                "Chicken breast",
                "buy 2 KG take 1 KG or free",
                "App/images/SalesPictures/butcher_sale_7.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                9,
                "Spring chicken",
                "10% discount",
                "App/images/SalesPictures/butcher_sale_8.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                10,
                "Werther's original",
                "Buy 5 get 1 fo free",
                "App/images/SalesPictures/candies_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                10,
                "Skittles",
                "20% discount on the family size pack",
                "App/images/SalesPictures/candies_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                10,
                "Jelly bean candy",
                "15% discount",
                "App/images/SalesPictures/candies_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                10,
                "Sour strips",
                "Buy 10 packs get 2 for free",
                "App/images/SalesPictures/candies_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                10,
                "M&M",
                "20% discount on the family size pack",
                "App/images/SalesPictures/candies_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                10,
                "Pez",
                "Buy 4 and get bubble head for free",
                "App/images/SalesPictures/candies_sale_6.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                10,
                "Sour patch",
                "10% discount on Mondays",
                "App/images/SalesPictures/candies_sale_7.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                19,
                11,
                "Changeable dumbbell",
                "300$ for only two weeks",
                "App/images/SalesPictures/fitness_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                19,
                11,
                "2 KG dumbbells",
                "In 40 nis only for this mounth",
                "App/images/SalesPictures/fitness_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                19,
                11,
                "2 KG dumbbell",
                "In 25 nis only for this mounth",
                "App/images/SalesPictures/fitness_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                19,
                11,
                "Full bench press set",
                "Free delivery until the end of the year",
                "App/images/SalesPictures/fitness_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                19,
                11,
                "Adjustment dumbbell",
                "10% discount and free shipment only for 2 weeks",
                "App/images/SalesPictures/fitness_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                19,
                11,
                "Plate set",
                "10 nis per 1 KG only for this week",
                "App/images/SalesPictures/fitness_sale_6.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                12,
                "Clear whey",
                "25% discount when buying over 220 nis",
                "App/images/SalesPictures/myprotein_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                12,
                "Layerd protein bar",
                "1 + 1 only for this week",
                "App/images/SalesPictures/myprotein_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                12,
                "Whey protein",
                "15% discount for this mounth",
                "App/images/SalesPictures/myprotein_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                12,
                "Brownies",
                "1 + 1 only for this week",
                "App/images/SalesPictures/myprotein_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                12,
                "The whey",
                "Buy 2 get 1 for free",
                "App/images/SalesPictures/myprotein_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                12,
                "Multi vitamin",
                "30% discount",
                "App/images/SalesPictures/myprotein_sale_6.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                12,
                "Bcaa",
                "Buy 6 and get 20% off",
                "App/images/SalesPictures/myprotein_sale_7.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                13,
                "Markers",
                "10% discount",
                "App/images/SalesPictures/crafting_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                13,
                "Canvas",
                "Buy 2 get 1 for free",
                "App/images/SalesPictures/crafting_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                13,
                "Oil paint",
                "Buy the big set and get free small canvas",
                "App/images/SalesPictures/crafting_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                13,
                "Raping paper",
                "20% discount",
                "App/images/SalesPictures/crafting_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                13,
                "Scissors",
                "1 + 1 for 2 weeks only",
                "App/images/SalesPictures/crafting_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                13,
                "Painting brushes",
                "Buy 3 and the 4th one is free",
                "App/images/SalesPictures/crafting_sale_6.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Square perline chocolate",
                "15% when buying 1 KG or more",
                "App/images/SalesPictures/chocolate_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Chocolate bar",
                "Buy 3 and get 1 for free",
                "App/images/SalesPictures/chocolate_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Artistic perline set",
                "20% discount on the large box",
                "App/images/SalesPictures/chocolate_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Perlines",
                "Buy 10 get 2 for free",
                "App/images/SalesPictures/chocolate_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Valentines box",
                "30% discount only this week",
                "App/images/SalesPictures/chocolate_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Pink bar",
                "15 % discount on valentine's day",
                "App/images/SalesPictures/chocolate_sale_6.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Chocolate spread",
                "15% discount when buying the large size",
                "App/images/SalesPictures/chocolate_sale_7.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Chocolate cake",
                "20%discount on Sunday's",
                "App/images/SalesPictures/chocolate_sale_8.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                14,
                "Artistic perlines",
                "10% off",
                "App/images/SalesPictures/chocolate_sale_9.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                18,
                15,
                "Milk",
                "20% discount when buying 2 liters or more",
                "App/images/SalesPictures/dairy_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                18,
                15,
                "Parmesan",
                "1 + 1 on the small size",
                "App/images/SalesPictures/dairy_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                18,
                15,
                "Cream cheese",
                "10% discount on weekends",
                "App/images/SalesPictures/dairy_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                18,
                15,
                "Cheddar cheese",
                "10% discount on weekends",
                "App/images/SalesPictures/dairy_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                18,
                15,
                "Gorgonzola",
                "Buy 2 get 1 for free",
                "App/images/SalesPictures/dairy_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                18,
                15,
                "Yugort",
                "10% discount",
                "App/images/SalesPictures/dairy_sale_6.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                18,
                15,
                "Ice cream",
                "Buy 2 KG and get half kG for free",
                "App/images/SalesPictures/dairy_sale_7.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                18,
                15,
                "Mozzarella",
                "Buy the 2 KG pack and get 20% off",
                "App/images/SalesPictures/dairy_sale_8.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                10,
                16,
                "Norweign salmon",
                "20% discount after 4pm",
                "App/images/SalesPictures/butcher_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                10,
                16,
                "Lavrak",
                "15% discount after 4pm",
                "App/images/SalesPictures/butcher_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                10,
                16,
                "Tuna",
                "Buy 1 KG and get 10% discount",
                "App/images/SalesPictures/butcher_sale_6.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                20,
                17,
                "Shushi knife",
                "15% discount only on weekends",
                "App/images/SalesPictures/knife_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                20,
                17,
                "Butcher knife",
                "10% discount only on weekends",
                "App/images/SalesPictures/knife_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                20,
                17,
                "Knife set",
                "20% discount on the holyday's",
                "App/images/SalesPictures/knife_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                20,
                17,
                "Sharpener",
                "10 discount",
                "App/images/SalesPictures/knife_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                20,
                18,
                "The basic",
                """10% discount""",
                "App/images/SalesPictures/grill_sale_1.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                20,
                18,
                "Old school",
                "Buy 1 and get 5 KG charcoal for free",
                "App/images/SalesPictures/grill_sale_2.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                20,
                18,
                "Outdoor grill",
                """Buy 1 and get free 2 KG charcoal""",
                "App/images/SalesPictures/grill_sale_3.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                20,
                18,
                "Smokery",
                "20% discount only for this weekend",
                "App/images/SalesPictures/grill_sale_4.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                20,
                18,
                "A giant smokery",
                "25% discount ",
                "App/images/SalesPictures/grill_sale_5.jpg",
                Sale.SaleStatus.APPROVED,
            ),
            (
                21,
                19,
                "Elegant shoe",
                "10% on Mondays",
                "App/images/SalesPictures/shoe_store_1.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                21,
                19,
                "Running shoe",
                "25% discount for the second per",
                "App/images/SalesPictures/shoe_store_3.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                21,
                19,
                "Crossfit shoe",
                "80% discount when buying above 400 NIS",
                "App/images/SalesPictures/shoe_store_2.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                21,
                19,
                "Football shoe",
                "1+1 for the all week",
                "App/images/SalesPictures/shoe_store_4.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                21,
                20,
                "Gyn set's",
                "10% discount on gym set's",
                "App/images/SalesPictures/sports_wear_1.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                21,
                20,
                "Football set's",
                "20% discount on football set's",
                "App/images/SalesPictures/sports_wear_2.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                21,
                20,
                "Socks",
                "25% discount",
                "App/images/SalesPictures/sports_wear_3.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                21,
                20,
                "Winter colection",
                "10% off for one week",
                "App/images/SalesPictures/sports_wear_4.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                16,
                21,
                "Basketball",
                "10% discount",
                "App/images/SalesPictures/sports_equipment_2.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                16,
                21,
                "Baseball",
                "Buy 4 and get 1 for free",
                "App/images/SalesPictures/sports_equipment_2.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                16,
                21,
                "Tennis racket",
                "25% discount on the X series",
                "App/images/SalesPictures/sports_equipment_3.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                16,
                21,
                "Pingpong racket",
                "Buy 3 and the 4th on is free",
                "App/images/SalesPictures/sports_equipment_4.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                15,
                22,
                "Shuckels",
                "Set of 6 in price of 4!!",
                "App/images/SalesPictures/climbing_store_1.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                15,
                22,
                "Fuul basic body set",
                "50% discount ",
                "App/images/SalesPictures/climbing_store_2.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                15,
                22,
                "Rope",
                "25% discount for the all weekend",
                "App/images/SalesPictures/climbing_store_3.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                15,
                22,
                "Harness",
                "10% discount for members",
                "App/images/SalesPictures/climbing_store_4.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                15,
                22,
                "Helmet",
                "10% discount for members",
                "App/images/SalesPictures/climbing_store_5.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                14,
                23,
                "Snorkel with mask",
                "10% discount for new members",
                "App/images/SalesPictures/diving_store_1.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                14,
                23,
                "Diving vest + octupus",
                "25% discount untill the end of the year!",
                "App/images/SalesPictures/diving_store_2.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                14,
                23,
                "Ballon",
                "10% discount",
                "App/images/SalesPictures/diving_store_3.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                14,
                23,
                "Free diving set",
                "10% discount when buying above 400 nis",
                "App/images/SalesPictures/diving_store_4.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                14,
                23,
                "Deep diving vest",
                "40% discount",
                "App/images/SalesPictures/diving_store_5.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                16,
                24,
                "2 person plate",
                "20% on monday's",
                "App/images/SalesPictures/bones_restaurant_1.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                16,
                24,
                "Starter on the house",
                "Free Starter when order nore than 200 nis",
                "App/images/SalesPictures/bones_restaurant_2.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                16,
                24,
                "Family ",
                "35% discount on Wednesday's",
                "App/images/SalesPictures/bones_restaurant_3.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                16,
                24,
                "Business lunch",
                "Main dish and a side in 65 nis between 12:00-17:00",
                "App/images/SalesPictures/bones_restaurant_4.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                14,
                26,
                "Coffee and bakery",
                "In 10 nis only!!",
                "App/images/SalesPictures/coffee_house_1.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                14,
                26,
                "multi use Take Away cup",
                "In 25 nis only!!!",
                "App/images/SalesPictures/coffee_house_2.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                14,
                26,
                "family pack",
                "Buy 3 coffee and get 1 for 50% discount",
                "App/images/SalesPictures/coffee_house_3.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                14,
                26,
                "Business lunch",
                "Buy main dish and get free coffee",
                "App/images/SalesPictures/coffee_house_4.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                1,
                "Private session",
                "15% discount on monday's training",
                "App/images/SalesPictures/matt_does_fitness_1.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                1,
                "Group session",
                "20% discount of 10 persons group",
                "App/images/SalesPictures/matt_does_fitness_2.jfif",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                2,
                "Single entry",
                "30 nis",
                "App/images/SalesPictures/space_florentin_1.png",
                Sale.SaleStatus.APPROVED,
            ),
            (
                22,
                2,
                "Yearly membership",
                "99 nis per month for new members",
                "App/images/SalesPictures/space_florentin_2.jfif",
                Sale.SaleStatus.APPROVED,
            ),
        ]

        with transaction.atomic():
            for (
                profile_id,
                business_id,
                title,
                description,
                picture,
                is_confirmed,
            ) in sales_test_data:
                sale = Sale(
                    profile=get_object_or_404(Profile, pk=profile_id),
                    business=get_object_or_404(Business, pk=business_id),
                    title=title,
                    picture=picture,
                    description=description,
                    is_confirmed=is_confirmed,
                )
                sale.save()

    operations = [
        migrations.RunPython(generate_data),
    ]
